-- =============================================================================
-- Tratamiento-app: modelo relacional (PostgreSQL 17)
-- Relacional para todo lo que se cruza (recetas, entregas, compras, stock).
-- Tipos de documento solo donde el dato es un documento:
--   receta_item.horarios   TIME[]  (siempre se lee junto con su medicamento)
--   visita.extraccion_ia   JSONB   (salida cruda de ai.py, esquema variable)
-- =============================================================================

CREATE TYPE origen_receta  AS ENUM ('manual', 'ia', 'simulado');
CREATE TYPE estado_entrega AS ENUM ('completo', 'parcial', 'no');
CREATE TYPE modo_compra    AS ENUM ('recoger', 'envio');
CREATE TYPE tipo_aviso     AS ENUM ('toma', 'compra', 'cita');

-- ---------------------------------------------------------------------------
-- Catálogos: farmacias, medicinas, stock, promociones, condiciones
-- ---------------------------------------------------------------------------
-- Farmaenlace: tablas `farmacias`, `medicinas` y `stock` (prioritarias).
-- Su DATA vive en db/datos_farmaenlace/ (farmacias.sql -> medicinas.sql -> stock.sql), no en init/.
-- Los uid de medicinas (FE-00001...) y de stock (FE-STK-000001...) son PROVISIONALES.
CREATE TABLE farmacias (
    uid       INTEGER PRIMARY KEY,           -- número único
    nombre    TEXT NOT NULL,
    direccion TEXT NOT NULL,
    lat       DOUBLE PRECISION NOT NULL CHECK (lat  BETWEEN -90  AND 90),
    long      DOUBLE PRECISION NOT NULL CHECK (long BETWEEN -180 AND 180),
    horario   TEXT                           -- "Lun-vie 8:00-20:30; sáb y dom 9:00-19:00"
);

CREATE TABLE medicinas (
    uid                 TEXT PRIMARY KEY,    -- FE-00001 (código a nivel Farmaenlace)
    nombre              TEXT NOT NULL,       -- principio activo: "Losartán"
    concentracion       TEXT NOT NULL,       -- "50 mg", "100 UI/ml, 10 ml"
    unidad              TEXT NOT NULL,       -- tableta, cápsula, frasco, pluma, inhalador...
    grupo               TEXT,                -- "Presión y corazón", "Diabetes"...
    efectos_secundarios TEXT,
    laboratorio         TEXT,
    UNIQUE (nombre, concentracion)
);
CREATE INDEX medicinas_nombre_idx ON medicinas (lower(nombre));

CREATE TABLE stock (
    uid          TEXT PRIMARY KEY,           -- FE-STK-000001 (código propio del stock)
    uid_medicina TEXT    NOT NULL REFERENCES medicinas (uid),
    uid_farmacia INTEGER NOT NULL REFERENCES farmacias (uid) ON DELETE CASCADE,
    cantidad     INTEGER NOT NULL CHECK (cantidad >= 0),   -- unidades disponibles
    unidad       TEXT NOT NULL,                            -- tabletas, frascos...
    UNIQUE (uid_medicina, uid_farmacia)
);
CREATE INDEX stock_farmacia_idx ON stock (uid_farmacia);

CREATE TABLE promocion (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo         TEXT NOT NULL,
    detalle        TEXT NOT NULL,
    uid_medicina   TEXT REFERENCES medicinas (uid),
    vigente_hasta  DATE NOT NULL
);

CREATE TABLE condicion (
    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE
);

-- ---------------------------------------------------------------------------
-- Paciente
-- ---------------------------------------------------------------------------
CREATE TABLE paciente (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            TEXT NOT NULL,
    fecha_nacimiento  DATE NOT NULL,
    cuidador          TEXT,
    tiene_iess        BOOLEAN NOT NULL DEFAULT FALSE,
    consentimiento    BOOLEAN NOT NULL DEFAULT FALSE,
    consentimiento_en TIMESTAMPTZ,
    lat               NUMERIC(10, 7) NOT NULL,
    lng               NUMERIC(10, 7) NOT NULL,
    creado_en         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (NOT consentimiento OR consentimiento_en IS NOT NULL)
);

-- Login de la demo: un usuario ve solo la data de su paciente
CREATE TABLE usuario (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id   INT NOT NULL UNIQUE REFERENCES paciente (id) ON DELETE CASCADE,
    email         TEXT NOT NULL,
    password_hash TEXT NOT NULL,            -- formato werkzeug (pbkdf2:sha256)
    creado_en     TIMESTAMPTZ NOT NULL DEFAULT now(),
    ultimo_login  TIMESTAMPTZ
);
CREATE UNIQUE INDEX usuario_email_idx ON usuario (lower(email));

CREATE TABLE paciente_condicion (
    paciente_id  INT NOT NULL REFERENCES paciente (id) ON DELETE CASCADE,
    condicion_id INT NOT NULL REFERENCES condicion (id),
    PRIMARY KEY (paciente_id, condicion_id)
);

CREATE TABLE cita (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id INT NOT NULL REFERENCES paciente (id) ON DELETE CASCADE,
    fecha_hora  TIMESTAMPTZ NOT NULL,
    motivo      TEXT
);
CREATE INDEX cita_paciente_fecha_idx ON cita (paciente_id, fecha_hora);

-- ---------------------------------------------------------------------------
-- Receta (visita) e ítems
-- ---------------------------------------------------------------------------
CREATE TABLE visita (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id   INT NOT NULL REFERENCES paciente (id) ON DELETE CASCADE,
    fecha         DATE NOT NULL,
    origen        origen_receta NOT NULL DEFAULT 'manual',
    extraccion_ia JSONB,
    UNIQUE (paciente_id, fecha) -- app.py reemplaza la receta del mismo día
);

CREATE TABLE receta_item (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visita_id      INT NOT NULL REFERENCES visita (id) ON DELETE CASCADE,
    uid_medicina   TEXT NOT NULL REFERENCES medicinas (uid),
    dosis_mg       INT NOT NULL CHECK (dosis_mg >= 0),
    cada_horas     INT NOT NULL CHECK (cada_horas > 0),
    dias           INT NOT NULL CHECK (dias > 0),
    horarios       TIME[] NOT NULL CHECK (cardinality(horarios) > 0),
    UNIQUE (visita_id, uid_medicina)
);

-- ---------------------------------------------------------------------------
-- Abastecimiento: entrega del IESS y compras en farmacia
-- ---------------------------------------------------------------------------
CREATE TABLE entrega_iess (
    receta_item_id     INT PRIMARY KEY REFERENCES receta_item (id) ON DELETE CASCADE,
    estado             estado_entrega NOT NULL,
    unidades_recibidas INT NOT NULL CHECK (unidades_recibidas >= 0),
    registrado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (estado <> 'no' OR unidades_recibidas = 0)
);

CREATE TABLE compra (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id INT NOT NULL REFERENCES paciente (id) ON DELETE CASCADE,
    visita_id   INT NOT NULL REFERENCES visita (id) ON DELETE CASCADE,
    uid_farmacia INT NOT NULL REFERENCES farmacias (uid),
    modo        modo_compra NOT NULL,
    creado_en   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE compra_item (
    compra_id      INT NOT NULL REFERENCES compra (id) ON DELETE CASCADE,
    receta_item_id INT NOT NULL REFERENCES receta_item (id) ON DELETE CASCADE,
    unidades       INT NOT NULL CHECK (unidades > 0),
    PRIMARY KEY (compra_id, receta_item_id)
);

-- ---------------------------------------------------------------------------
-- Adherencia y avisos
-- ---------------------------------------------------------------------------
CREATE TABLE toma (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receta_item_id INT NOT NULL REFERENCES receta_item (id) ON DELETE CASCADE,
    fecha          DATE NOT NULL,
    hora           TIME NOT NULL,
    tomada_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (receta_item_id, fecha, hora)
);

CREATE TABLE aviso (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id INT NOT NULL REFERENCES paciente (id) ON DELETE CASCADE,
    tipo        tipo_aviso NOT NULL,
    titulo      TEXT NOT NULL,
    cuerpo      TEXT NOT NULL,
    corto       TEXT,        -- texto de la notificación del sistema
    url         TEXT NOT NULL,
    clave       TEXT,        -- "AAAA-MM-DD|Med@HH:MM|toma": evita repetir avisos automáticos
    creado_en   TIMESTAMPTZ NOT NULL DEFAULT now(),
    mostrado_en TIMESTAMPTZ, -- NULL = en cola
    UNIQUE (paciente_id, clave)
);
CREATE INDEX aviso_cola_idx ON aviso (paciente_id) WHERE mostrado_en IS NULL;

-- =============================================================================
-- Vistas: replican las fórmulas de logic.py
-- =============================================================================

-- logic.visita_actual(): la receta más reciente de cada paciente
CREATE VIEW v_visita_actual AS
SELECT DISTINCT ON (paciente_id) *
FROM visita
ORDER BY paciente_id, fecha DESC;

-- logic.tomas_por_dia() / total_recetado()
CREATE VIEW v_receta_item_total AS
SELECT ri.id                             AS receta_item_id,
       ri.visita_id,
       v.paciente_id,
       v.fecha                           AS visita_fecha,
       m.nombre                          AS nombre,
       ri.dosis_mg,
       ri.cada_horas,
       ri.dias,
       ri.horarios,
       cardinality(ri.horarios)          AS tomas_por_dia,
       cardinality(ri.horarios) * ri.dias AS total
FROM receta_item ri
JOIN visita v      ON v.id = ri.visita_id
JOIN medicinas m   ON m.uid = ri.uid_medicina;

-- logic.recibido_iess() + comprado() = inventario(); dias_restantes()
CREATE VIEW v_inventario AS
SELECT x.*,
       x.recibido_iess + x.comprado                         AS inventario,
       (x.recibido_iess + x.comprado) / x.tomas_por_dia     AS dias_restantes
FROM (
    SELECT t.*,
           p.tiene_iess,
           e.estado                                          AS estado_iess,
           e.unidades_recibidas,
           CASE WHEN p.tiene_iess AND e.estado <> 'no' THEN e.unidades_recibidas ELSE 0 END
                                                             AS recibido_iess,
           COALESCE((SELECT sum(ci.unidades)
                     FROM compra_item ci
                     WHERE ci.receta_item_id = t.receta_item_id), 0)::INT AS comprado
    FROM v_receta_item_total t
    JOIN paciente p          ON p.id = t.paciente_id
    LEFT JOIN entrega_iess e ON e.receta_item_id = t.receta_item_id
) x;

-- logic.falta_respuesta_iess(): paciente con IESS cuya receta actual no tiene entregas
CREATE VIEW v_falta_respuesta_iess AS
SELECT va.paciente_id, va.id AS visita_id, va.fecha
FROM v_visita_actual va
JOIN paciente p ON p.id = va.paciente_id
WHERE p.tiene_iess
  AND NOT EXISTS (SELECT 1
                  FROM receta_item ri
                  JOIN entrega_iess e ON e.receta_item_id = ri.id
                  WHERE ri.visita_id = va.id);

-- logic.faltantes(): solo receta actual y solo si el IESS ya respondió
CREATE VIEW v_faltantes AS
SELECT i.paciente_id,
       i.visita_id,
       i.receta_item_id,
       i.nombre,
       i.dosis_mg,
       i.total,
       i.inventario,
       i.total - i.inventario AS falta,
       CASE
           WHEN NOT i.tiene_iess      THEN 'Sin IESS: se compra todo'
           WHEN i.estado_iess = 'no'  THEN 'Sin stock en el IESS'
           WHEN i.estado_iess IS NOT NULL
                THEN 'El IESS entregó ' || i.unidades_recibidas || ' de ' || i.total
           ELSE 'Pendiente'
       END AS motivo
FROM v_inventario i
JOIN v_visita_actual va ON va.id = i.visita_id
WHERE i.total - i.inventario > 0
  AND NOT EXISTS (SELECT 1 FROM v_falta_respuesta_iess f WHERE f.visita_id = i.visita_id);

-- Edad calculada (el front muestra "edad")
CREATE VIEW v_paciente AS
SELECT p.*,
       date_part('year', age(CURRENT_DATE, p.fecha_nacimiento))::INT AS edad,
       (SELECT array_agg(c.nombre ORDER BY c.nombre)
        FROM paciente_condicion pc JOIN condicion c ON c.id = pc.condicion_id
        WHERE pc.paciente_id = p.id)                                   AS condiciones,
       (SELECT min(ci.fecha_hora) FROM cita ci
        WHERE ci.paciente_id = p.id AND ci.fecha_hora > now())          AS proxima_cita
FROM paciente p;
