-- =============================================================================
-- Módulo de abastecimiento continuo (fase 1): saldo real de medicación,
-- reloj de la demo, cuidadores y productos relacionados.
-- Corre después de las semillas de pacientes (003-005) y antes de 999_sync_sequences.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Reloj de la demo: fecha de referencia compartida por la UI, la API y el evaluador.
-- Sin fila (o valor NULL) = fecha real. "Simular +N días" la mueve hacia adelante.
-- ---------------------------------------------------------------------------
CREATE TABLE config_demo (
    clave TEXT PRIMARY KEY,
    valor TEXT
);

CREATE FUNCTION fecha_referencia() RETURNS DATE
LANGUAGE sql STABLE AS $$
    SELECT COALESCE((SELECT valor::DATE FROM config_demo WHERE clave = 'fecha_referencia'), CURRENT_DATE)
$$;

-- ---------------------------------------------------------------------------
-- Paciente: datos que necesita el monitoreo
-- ---------------------------------------------------------------------------
ALTER TABLE paciente
    ADD COLUMN umbral_dias        INT     NOT NULL DEFAULT 7 CHECK (umbral_dias > 0),  -- avisar con N días de anticipación
    ADD COLUMN direccion_entrega  TEXT,
    ADD COLUMN movilidad_reducida BOOLEAN NOT NULL DEFAULT FALSE;

-- Medicamentos controlados (psicotrópicos/estupefacientes): retiro presencial con receta especial,
-- no van por delivery. PROVISIONAL: validar la lista con la normativa ARCSA antes de producción.
ALTER TABLE medicinas ADD COLUMN controlado BOOLEAN NOT NULL DEFAULT FALSE;
UPDATE medicinas SET controlado = TRUE WHERE nombre IN ('Tramadol', 'Clonazepam', 'Alprazolam');

INSERT INTO condicion (id, nombre) VALUES
    (6, 'Cuadriplejia'),
    (7, 'Enfermedad de Parkinson'),
    (8, 'Alzheimer'),
    (9, 'Cuidados paliativos');

-- ---------------------------------------------------------------------------
-- Cuidadores: un cuidador puede tener varios pacientes y un paciente varios cuidadores
-- ---------------------------------------------------------------------------
CREATE TABLE cuidador (
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    TEXT NOT NULL,
    email     TEXT NOT NULL,
    telefono  TEXT,
    lat       NUMERIC(10, 7) NOT NULL,     -- desde dónde sale a comprar (para el ranking de farmacias)
    lng       NUMERIC(10, 7) NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX cuidador_email_idx ON cuidador (lower(email));

CREATE TABLE paciente_cuidador (
    paciente_id INT  NOT NULL REFERENCES paciente (id) ON DELETE CASCADE,
    cuidador_id INT  NOT NULL REFERENCES cuidador (id) ON DELETE CASCADE,
    rol         TEXT NOT NULL DEFAULT 'principal' CHECK (rol IN ('principal', 'apoyo')),
    parentesco  TEXT,                          -- "Hija", "Enfermera", ...
    PRIMARY KEY (paciente_id, cuidador_id)
);

-- ---------------------------------------------------------------------------
-- Productos relacionados (no medicamentos) y reglas de sugerencia
-- ---------------------------------------------------------------------------
CREATE TABLE producto (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      TEXT NOT NULL UNIQUE,
    categoria   TEXT NOT NULL,
    presentacion TEXT
);

CREATE TABLE regla_sugerencia (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    condicion_id   INT  REFERENCES condicion (id) ON DELETE CASCADE,
    grupo_medicina TEXT,                       -- medicinas.grupo
    producto_id    INT  NOT NULL REFERENCES producto (id) ON DELETE CASCADE,
    motivo         TEXT NOT NULL,
    CHECK ((condicion_id IS NULL) <> (grupo_medicina IS NULL))  -- por condición O por grupo
);

INSERT INTO producto (id, nombre, categoria, presentacion) VALUES
    (1,  'Pañales para adulto',                 'Higiene',          'Paquete x10'),
    (2,  'Protector de cama desechable',        'Higiene',          'Paquete x10'),
    (3,  'Crema barrera con óxido de zinc',     'Cuidado de piel',  'Tubo 110 g'),
    (4,  'Cojín antiescaras',                   'Movilidad',        'Unidad'),
    (5,  'Gasas estériles',                     'Curaciones',       'Caja x100'),
    (6,  'Pastillero semanal con alarma',       'Adherencia',       'Unidad'),
    (7,  'Espesante para líquidos',             'Nutrición',        'Lata 225 g'),
    (8,  'Suplemento nutricional líquido',      'Nutrición',        'Botella 237 ml'),
    (9,  'Tiras reactivas de glucosa',          'Diabetes',         'Caja x50'),
    (10, 'Lancetas',                            'Diabetes',         'Caja x100'),
    (11, 'Tensiómetro digital de brazo',        'Monitoreo',        'Unidad'),
    (12, 'Toallitas húmedas para adulto',       'Higiene',          'Paquete x48'),
    (13, 'Guantes de examinación',              'Curaciones',       'Caja x100'),
    (14, 'Bolsa recolectora de orina',          'Urología',         'Unidad');

INSERT INTO regla_sugerencia (condicion_id, grupo_medicina, producto_id, motivo) VALUES
    (6, NULL, 1,  'Manejo de incontinencia en movilidad reducida'),
    (6, NULL, 2,  'Protege la cama en pacientes encamados'),
    (6, NULL, 3,  'Previene dermatitis por humedad'),
    (6, NULL, 4,  'Previene úlceras por presión en pacientes que pasan sentados o acostados'),
    (6, NULL, 13, 'Higiene del cuidador durante los cambios'),
    (9, NULL, 1,  'Confort en cuidados paliativos'),
    (9, NULL, 3,  'Cuidado de la piel en pacientes encamados'),
    (9, NULL, 5,  'Curaciones frecuentes'),
    (9, NULL, 8,  'Apoyo nutricional cuando disminuye el apetito'),
    (7, NULL, 6,  'Las dosis de levodopa son a horas fijas: la alarma ayuda a no saltarlas'),
    (7, NULL, 7,  'La dificultad para tragar es frecuente en Parkinson avanzado'),
    (8, NULL, 6,  'Ayuda al cuidador a controlar qué dosis ya se dio'),
    (8, NULL, 12, 'Higiene diaria en Alzheimer avanzado'),
    (2, NULL, 9,  'Control de glucosa en casa'),
    (2, NULL, 10, 'Necesarias para medir la glucosa'),
    (1, NULL, 11, 'Control de la presión en casa'),
    (NULL, 'Urología', 14, 'Complementa el tratamiento de vejiga neurogénica');

-- ---------------------------------------------------------------------------
-- Saldo real de medicación (receta vigente de cada paciente)
--   unidades_obtenidas = entregado por el IESS + comprado
--   fecha_agotamiento  = inicio de la receta + unidades_obtenidas / tomas por día
--   dias_restantes     = fecha_agotamiento - fecha_referencia()   (mínimo 0)
-- Supuestos: 1 tableta por toma y adherencia completa desde la fecha de la receta.
-- Debe dar lo mismo que abastecimiento/calculo.py (lo verifican las pruebas).
-- ---------------------------------------------------------------------------
CREATE VIEW v_saldo_medicacion AS
SELECT x.*,
       CASE
           WHEN x.sin_respuesta_iess              THEN 'sin_respuesta_iess'
           WHEN x.dias_restantes <= 0             THEN 'agotado'
           WHEN x.dias_restantes <= x.umbral_dias THEN 'por_agotarse'
           ELSE 'ok'
       END AS estado
FROM (
    SELECT i.paciente_id,
           i.visita_id,
           i.receta_item_id,
           i.nombre,
           i.dosis_mg,
           m.uid                                                     AS uid_medicina,
           m.concentracion,
           m.grupo,
           m.controlado,
           i.tomas_por_dia,
           i.dias                                                    AS dias_receta,
           i.visita_fecha                                            AS inicio,
           i.visita_fecha + i.dias                                   AS fin_tratamiento,
           i.recibido_iess,
           i.comprado,
           i.inventario                                              AS unidades_obtenidas,
           ref.hoy                                                   AS fecha_referencia,
           i.visita_fecha + i.inventario / i.tomas_por_dia           AS fecha_agotamiento,
           GREATEST(i.inventario - i.tomas_por_dia * GREATEST(ref.hoy - i.visita_fecha, 0), 0)
                                                                     AS saldo_unidades,
           GREATEST(i.visita_fecha + i.inventario / i.tomas_por_dia - ref.hoy, 0)
                                                                     AS dias_restantes,
           p.umbral_dias,
           (fr.visita_id IS NOT NULL)                                AS sin_respuesta_iess
    FROM v_inventario i
    JOIN v_visita_actual va  ON va.id = i.visita_id
    JOIN paciente p          ON p.id = i.paciente_id
    JOIN receta_item ri      ON ri.id = i.receta_item_id
    JOIN medicinas m         ON m.uid = ri.uid_medicina
    CROSS JOIN (SELECT fecha_referencia() AS hoy) ref
    LEFT JOIN v_falta_respuesta_iess fr ON fr.visita_id = i.visita_id
) x;
