-- =============================================================================
-- Módulo de abastecimiento (fase 2): alertas idempotentes y registro de eventos.
-- =============================================================================

-- Una alerta por paciente + medicamento + tipo + "día de referencia" (reloj de la demo):
-- el evaluador puede correr cada pocos minutos sin repetir avisos.
CREATE TABLE alerta (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id      INT  NOT NULL REFERENCES paciente (id) ON DELETE CASCADE,
    receta_item_id   INT  NOT NULL REFERENCES receta_item (id) ON DELETE CASCADE,
    -- por_agotarse / agotado / iess_sin_respuesta: una por día de referencia (recordatorio diario)
    -- entrega_iess_incompleta: una por receta (fecha_referencia = fecha de la receta)
    tipo             TEXT NOT NULL CHECK (tipo IN ('por_agotarse', 'agotado', 'iess_sin_respuesta',
                                                   'entrega_iess_incompleta')),
    fecha_referencia DATE NOT NULL,
    dias_restantes   INT,
    detalle          TEXT,
    evento_id        TEXT,                      -- evento que la comunicó
    creado_en        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (paciente_id, receta_item_id, tipo, fecha_referencia)
);
CREATE INDEX alerta_paciente_idx ON alerta (paciente_id, fecha_referencia DESC);

-- Todo lo que pasa por el bus (o por el despacho local): para la consola de demo y auditoría.
--   publicado : un componente emitió el evento
--   entregado : una regla lo llevó a un destino (notificador, webhook, Farmaenlace...)
--   recibido  : llegó desde afuera (callback de Farmaenlace)
--   interno   : registro de una ejecución (p. ej. EvaluacionEjecutada)
CREATE TABLE evento_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id   TEXT NOT NULL,
    direccion   TEXT NOT NULL CHECK (direccion IN ('publicado', 'entregado', 'recibido', 'interno')),
    detail_type TEXT NOT NULL,
    destino     TEXT,
    paciente_id INT,                            -- sin FK: el log sobrevive al reset de un paciente
    detail      JSONB NOT NULL,
    creado_en   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX evento_log_creado_idx ON evento_log (creado_en DESC);
CREATE INDEX evento_log_tipo_idx ON evento_log (detail_type, creado_en DESC);
