-- =============================================================================
-- Módulo de abastecimiento (fase 4): pedidos a Farmaenlace (delivery o retiro),
-- suscripción de abastecimiento automático y el mock de Farmaenlace.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Pedidos del módulo
-- ---------------------------------------------------------------------------
CREATE TABLE pedido (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id       INT  NOT NULL REFERENCES paciente (id) ON DELETE CASCADE,
    uid_farmacia      INT  NOT NULL REFERENCES farmacias (uid),
    modo              TEXT NOT NULL CHECK (modo IN ('delivery', 'retiro')),
    origen            TEXT NOT NULL CHECK (origen IN ('manual', 'suscripcion', 'api')),
    -- solicitado -> confirmado -> en_camino (delivery) | listo_para_retiro (retiro) -> entregado
    --            -> rechazado (sin stock) | cancelado
    estado            TEXT NOT NULL DEFAULT 'solicitado'
                      CHECK (estado IN ('solicitado', 'confirmado', 'en_camino', 'listo_para_retiro',
                                        'entregado', 'rechazado', 'cancelado')),
    direccion_entrega TEXT,
    ref_farmaenlace   TEXT,                  -- número de pedido que devuelve Farmaenlace
    eta               TIMESTAMPTZ,           -- llegada estimada (delivery) o hora en que estará listo (retiro)
    motivo            TEXT,                  -- motivo de rechazo / cancelación
    fecha_referencia  DATE NOT NULL,         -- día del reloj de la demo en que se creó
    creado_en         TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX pedido_paciente_idx ON pedido (paciente_id, creado_en DESC);

CREATE TABLE pedido_item (
    pedido_id      INT  NOT NULL REFERENCES pedido (id) ON DELETE CASCADE,
    uid_medicina   TEXT NOT NULL REFERENCES medicinas (uid),
    receta_item_id INT  REFERENCES receta_item (id) ON DELETE SET NULL,
    cantidad       INT  NOT NULL CHECK (cantidad > 0),
    PRIMARY KEY (pedido_id, uid_medicina)
);

CREATE VIEW v_pedido_abierto AS
SELECT p.*, pi.uid_medicina, pi.receta_item_id, pi.cantidad
FROM pedido p JOIN pedido_item pi ON pi.pedido_id = p.id
WHERE p.estado IN ('solicitado', 'confirmado', 'en_camino', 'listo_para_retiro');

-- ---------------------------------------------------------------------------
-- Suscripción: abastecimiento automático a domicilio
-- ---------------------------------------------------------------------------
CREATE TABLE suscripcion (
    paciente_id           INT PRIMARY KEY REFERENCES paciente (id) ON DELETE CASCADE,
    activa                BOOLEAN NOT NULL DEFAULT TRUE,
    dias_anticipacion     INT     NOT NULL DEFAULT 7 CHECK (dias_anticipacion > 0),  -- pedir con N días de margen
    uid_farmacia_preferida INT    REFERENCES farmacias (uid),                        -- NULL = la mejor sugerida
    metodo_pago           TEXT    NOT NULL DEFAULT 'contra_entrega',
    activada_en           TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizada_en        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- @paciente 14
-- Patricio Andrade (cuadriplejia) tiene el abastecimiento automático activo: con "Simular +20 días"
-- su medicación entra en el umbral y el evaluador genera el pedido a domicilio solo.
INSERT INTO suscripcion (paciente_id, dias_anticipacion, uid_farmacia_preferida) VALUES (14, 7, 1);
-- @fin

-- =============================================================================
-- Mock de Farmaenlace: su propio esquema (en la realidad es otro sistema).
-- Recibe la demanda prevista y los pedidos, reserva stock y responde por callback.
-- =============================================================================
CREATE SCHEMA farmaenlace;

CREATE TABLE farmaenlace.demanda (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id       TEXT,
    farmacia_id     INT  NOT NULL,
    uid_medicina    TEXT NOT NULL,
    nombre          TEXT NOT NULL,
    cantidad        INT  NOT NULL,
    fecha_necesidad DATE,
    recibido_en     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE farmaenlace.pedido (
    ref             TEXT PRIMARY KEY,           -- FE-PED-000001
    pedido_origen   INT  NOT NULL,              -- id del pedido en el módulo
    farmacia_id     INT  NOT NULL,
    modo            TEXT NOT NULL,
    estado          TEXT NOT NULL,
    items           JSONB NOT NULL,
    cliente         JSONB NOT NULL,             -- nombre, dirección, teléfono (solo con consentimiento)
    eta             TIMESTAMPTZ,
    motivo          TEXT,
    creado_en       TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE SEQUENCE farmaenlace.pedido_ref_seq;
