-- Catálogo de medicinas (187 presentaciones, 16 grupos), incluye crónicas: insulina, levodopa, anticoagulantes, etc.
-- uid FE-00001... es PROVISIONAL: no son códigos reales de Farmaenlace.
-- efectos_secundarios: información general por principio activo; validar con un químico farmacéutico.
-- laboratorio: marca/fabricante original más conocido del principio activo ("Genfar" = genérico por defecto).
--   NO viene del catálogo de Farmaenlace; confirmar antes de presentarlo como dato real.
-- La tabla se crea en db/init/001_schema.sql.

INSERT INTO medicinas (uid, nombre, concentracion, unidad, grupo, efectos_secundarios, laboratorio) VALUES
 ('FE-00001', 'Losartán', '50 mg', 'tableta', 'Presión y corazón', 'Mareo, dolor de cabeza, cansancio', 'MSD'),
 ('FE-00002', 'Losartán', '100 mg', 'tableta', 'Presión y corazón', 'Mareo, dolor de cabeza, cansancio', 'MSD'),
 ('FE-00003', 'Valsartán', '80 mg', 'tableta', 'Presión y corazón', 'Mareo, dolor de cabeza, cansancio', 'Novartis'),
 ('FE-00004', 'Valsartán', '160 mg', 'tableta', 'Presión y corazón', 'Mareo, dolor de cabeza, cansancio', 'Novartis'),
 ('FE-00005', 'Enalapril', '5 mg', 'tableta', 'Presión y corazón', 'Tos seca, mareo, dolor de cabeza', 'MSD'),
 ('FE-00006', 'Enalapril', '10 mg', 'tableta', 'Presión y corazón', 'Tos seca, mareo, dolor de cabeza', 'MSD'),
 ('FE-00007', 'Enalapril', '20 mg', 'tableta', 'Presión y corazón', 'Tos seca, mareo, dolor de cabeza', 'MSD'),
 ('FE-00008', 'Captopril', '25 mg', 'tableta', 'Presión y corazón', 'Tos seca, mareo, alteración del gusto', 'Bristol-Myers Squibb'),
 ('FE-00009', 'Lisinopril', '10 mg', 'tableta', 'Presión y corazón', 'Tos seca, mareo, dolor de cabeza', 'AstraZeneca'),
 ('FE-00010', 'Lisinopril', '20 mg', 'tableta', 'Presión y corazón', 'Tos seca, mareo, dolor de cabeza', 'AstraZeneca'),
 ('FE-00011', 'Amlodipino', '5 mg', 'tableta', 'Presión y corazón', 'Hinchazón de tobillos, dolor de cabeza, enrojecimiento de la cara', 'Pfizer'),
 ('FE-00012', 'Amlodipino', '10 mg', 'tableta', 'Presión y corazón', 'Hinchazón de tobillos, dolor de cabeza, enrojecimiento de la cara', 'Pfizer'),
 ('FE-00013', 'Nifedipino', '30 mg', 'tableta', 'Presión y corazón', 'Dolor de cabeza, hinchazón de tobillos, enrojecimiento de la cara', 'Bayer'),
 ('FE-00014', 'Hidroclorotiazida', '25 mg', 'tableta', 'Presión y corazón', 'Aumento de la orina, mareo, calambres', 'Genfar'),
 ('FE-00015', 'Furosemida', '40 mg', 'tableta', 'Presión y corazón', 'Aumento de la orina, mareo, calambres', 'Sanofi'),
 ('FE-00016', 'Espironolactona', '25 mg', 'tableta', 'Presión y corazón', 'Potasio alto, mareo, sensibilidad en las mamas', 'Pfizer'),
 ('FE-00017', 'Espironolactona', '100 mg', 'tableta', 'Presión y corazón', 'Potasio alto, mareo, sensibilidad en las mamas', 'Pfizer'),
 ('FE-00018', 'Atenolol', '50 mg', 'tableta', 'Presión y corazón', 'Cansancio, manos frías, pulso lento', 'AstraZeneca'),
 ('FE-00019', 'Atenolol', '100 mg', 'tableta', 'Presión y corazón', 'Cansancio, manos frías, pulso lento', 'AstraZeneca'),
 ('FE-00020', 'Bisoprolol', '2.5 mg', 'tableta', 'Presión y corazón', 'Cansancio, mareo, pulso lento', 'Merck'),
 ('FE-00021', 'Bisoprolol', '5 mg', 'tableta', 'Presión y corazón', 'Cansancio, mareo, pulso lento', 'Merck'),
 ('FE-00022', 'Bisoprolol', '10 mg', 'tableta', 'Presión y corazón', 'Cansancio, mareo, pulso lento', 'Merck'),
 ('FE-00023', 'Carvedilol', '6.25 mg', 'tableta', 'Presión y corazón', 'Mareo, cansancio, pulso lento', 'Roche'),
 ('FE-00024', 'Carvedilol', '12.5 mg', 'tableta', 'Presión y corazón', 'Mareo, cansancio, pulso lento', 'Roche'),
 ('FE-00025', 'Carvedilol', '25 mg', 'tableta', 'Presión y corazón', 'Mareo, cansancio, pulso lento', 'Roche'),
 ('FE-00026', 'Metoprolol', '50 mg', 'tableta', 'Presión y corazón', 'Cansancio, mareo, pulso lento', 'AstraZeneca'),
 ('FE-00027', 'Metoprolol', '100 mg', 'tableta', 'Presión y corazón', 'Cansancio, mareo, pulso lento', 'AstraZeneca'),
 ('FE-00028', 'Propranolol', '40 mg', 'tableta', 'Presión y corazón', 'Cansancio, pulso lento, manos frías', 'AstraZeneca'),
 ('FE-00029', 'Digoxina', '0.25 mg', 'tableta', 'Presión y corazón', 'Náuseas, visión borrosa, latidos irregulares', 'Aspen'),
 ('FE-00030', 'Amiodarona', '200 mg', 'tableta', 'Presión y corazón', 'Sensibilidad al sol, alteraciones de la tiroides, náuseas', 'Sanofi'),
 ('FE-00031', 'Isosorbide mononitrato', '20 mg', 'tableta', 'Presión y corazón', 'Dolor de cabeza, mareo, enrojecimiento de la cara', 'Genfar'),
 ('FE-00032', 'Isosorbide mononitrato', '60 mg', 'tableta', 'Presión y corazón', 'Dolor de cabeza, mareo, enrojecimiento de la cara', 'Genfar'),
 ('FE-00033', 'Nitroglicerina sublingual', '0.5 mg', 'tableta', 'Presión y corazón', 'Dolor de cabeza, mareo, enrojecimiento de la cara', 'Pfizer'),
 ('FE-00034', 'Atorvastatina', '10 mg', 'tableta', 'Colesterol', 'Molestias digestivas, dolor muscular, dolor de cabeza', 'Pfizer'),
 ('FE-00035', 'Atorvastatina', '20 mg', 'tableta', 'Colesterol', 'Molestias digestivas, dolor muscular, dolor de cabeza', 'Pfizer'),
 ('FE-00036', 'Atorvastatina', '40 mg', 'tableta', 'Colesterol', 'Molestias digestivas, dolor muscular, dolor de cabeza', 'Pfizer'),
 ('FE-00037', 'Atorvastatina', '80 mg', 'tableta', 'Colesterol', 'Molestias digestivas, dolor muscular, dolor de cabeza', 'Pfizer'),
 ('FE-00038', 'Rosuvastatina', '10 mg', 'tableta', 'Colesterol', 'Molestias digestivas, dolor muscular, dolor de cabeza', 'AstraZeneca'),
 ('FE-00039', 'Rosuvastatina', '20 mg', 'tableta', 'Colesterol', 'Molestias digestivas, dolor muscular, dolor de cabeza', 'AstraZeneca'),
 ('FE-00040', 'Simvastatina', '20 mg', 'tableta', 'Colesterol', 'Molestias digestivas, dolor muscular, dolor de cabeza', 'MSD'),
 ('FE-00041', 'Simvastatina', '40 mg', 'tableta', 'Colesterol', 'Molestias digestivas, dolor muscular, dolor de cabeza', 'MSD'),
 ('FE-00042', 'Fenofibrato', '200 mg', 'cápsula', 'Colesterol', 'Molestias digestivas, dolor muscular, alteración de enzimas del hígado', 'Abbott'),
 ('FE-00043', 'Ácido acetilsalicílico', '100 mg', 'tableta', 'Anticoagulantes y antiagregantes', 'Molestias de estómago, sangrado, moretones', 'Bayer'),
 ('FE-00044', 'Clopidogrel', '75 mg', 'tableta', 'Anticoagulantes y antiagregantes', 'Sangrado, moretones, molestias digestivas', 'Sanofi'),
 ('FE-00045', 'Warfarina', '5 mg', 'tableta', 'Anticoagulantes y antiagregantes', 'Sangrado, moretones', 'Bristol-Myers Squibb'),
 ('FE-00046', 'Rivaroxabán', '10 mg', 'tableta', 'Anticoagulantes y antiagregantes', 'Sangrado, moretones, anemia', 'Bayer'),
 ('FE-00047', 'Rivaroxabán', '15 mg', 'tableta', 'Anticoagulantes y antiagregantes', 'Sangrado, moretones, anemia', 'Bayer'),
 ('FE-00048', 'Rivaroxabán', '20 mg', 'tableta', 'Anticoagulantes y antiagregantes', 'Sangrado, moretones, anemia', 'Bayer'),
 ('FE-00049', 'Apixabán', '2.5 mg', 'tableta', 'Anticoagulantes y antiagregantes', 'Sangrado, moretones, náuseas', 'Bristol-Myers Squibb'),
 ('FE-00050', 'Apixabán', '5 mg', 'tableta', 'Anticoagulantes y antiagregantes', 'Sangrado, moretones, náuseas', 'Bristol-Myers Squibb'),
 ('FE-00051', 'Metformina', '500 mg', 'tableta', 'Diabetes', 'Náuseas, diarrea, dolor abdominal, sabor metálico', 'Merck'),
 ('FE-00052', 'Metformina', '850 mg', 'tableta', 'Diabetes', 'Náuseas, diarrea, dolor abdominal, sabor metálico', 'Merck'),
 ('FE-00053', 'Metformina', '1000 mg', 'tableta', 'Diabetes', 'Náuseas, diarrea, dolor abdominal, sabor metálico', 'Merck'),
 ('FE-00054', 'Glibenclamida', '5 mg', 'tableta', 'Diabetes', 'Bajón de azúcar, aumento de peso, náuseas', 'Sanofi'),
 ('FE-00055', 'Glimepirida', '2 mg', 'tableta', 'Diabetes', 'Bajón de azúcar, aumento de peso, náuseas', 'Sanofi'),
 ('FE-00056', 'Glimepirida', '4 mg', 'tableta', 'Diabetes', 'Bajón de azúcar, aumento de peso, náuseas', 'Sanofi'),
 ('FE-00057', 'Gliclazida', '30 mg', 'tableta', 'Diabetes', 'Bajón de azúcar, aumento de peso, náuseas', 'Servier'),
 ('FE-00058', 'Gliclazida', '80 mg', 'tableta', 'Diabetes', 'Bajón de azúcar, aumento de peso, náuseas', 'Servier'),
 ('FE-00059', 'Sitagliptina', '50 mg', 'tableta', 'Diabetes', 'Dolor de cabeza, congestión nasal, molestias digestivas', 'MSD'),
 ('FE-00060', 'Sitagliptina', '100 mg', 'tableta', 'Diabetes', 'Dolor de cabeza, congestión nasal, molestias digestivas', 'MSD'),
 ('FE-00061', 'Empagliflozina', '10 mg', 'tableta', 'Diabetes', 'Infecciones genitales, aumento de la orina, sed', 'Boehringer Ingelheim'),
 ('FE-00062', 'Empagliflozina', '25 mg', 'tableta', 'Diabetes', 'Infecciones genitales, aumento de la orina, sed', 'Boehringer Ingelheim'),
 ('FE-00063', 'Dapagliflozina', '10 mg', 'tableta', 'Diabetes', 'Infecciones genitales, aumento de la orina, sed', 'AstraZeneca'),
 ('FE-00064', 'Insulina NPH', '100 UI/ml, 10 ml', 'frasco', 'Diabetes', 'Bajón de azúcar, aumento de peso, reacción en la zona de inyección', 'Novo Nordisk'),
 ('FE-00065', 'Insulina regular', '100 UI/ml, 10 ml', 'frasco', 'Diabetes', 'Bajón de azúcar, aumento de peso, reacción en la zona de inyección', 'Novo Nordisk'),
 ('FE-00066', 'Insulina glargina', '100 UI/ml, 3 ml', 'pluma', 'Diabetes', 'Bajón de azúcar, aumento de peso, reacción en la zona de inyección', 'Sanofi'),
 ('FE-00067', 'Insulina lispro', '100 UI/ml, 3 ml', 'pluma', 'Diabetes', 'Bajón de azúcar, aumento de peso, reacción en la zona de inyección', 'Eli Lilly'),
 ('FE-00068', 'Insulina aspart', '100 UI/ml, 3 ml', 'pluma', 'Diabetes', 'Bajón de azúcar, aumento de peso, reacción en la zona de inyección', 'Novo Nordisk'),
 ('FE-00069', 'Tiras reactivas de glucosa', '50 tiras', 'caja', 'Diabetes', 'No aplica', 'Roche'),
 ('FE-00070', 'Lancetas', '100 unidades', 'caja', 'Diabetes', 'No aplica', 'Roche'),
 ('FE-00071', 'Levotiroxina', '25 mcg', 'tableta', 'Hormonas', 'Palpitaciones, nerviosismo, insomnio', 'Merck'),
 ('FE-00072', 'Levotiroxina', '50 mcg', 'tableta', 'Hormonas', 'Palpitaciones, nerviosismo, insomnio', 'Merck'),
 ('FE-00073', 'Levotiroxina', '100 mcg', 'tableta', 'Hormonas', 'Palpitaciones, nerviosismo, insomnio', 'Merck'),
 ('FE-00074', 'Metimazol', '5 mg', 'tableta', 'Hormonas', 'Erupción en la piel, dolor de articulaciones, náuseas', 'Merck'),
 ('FE-00075', 'Metimazol', '10 mg', 'tableta', 'Hormonas', 'Erupción en la piel, dolor de articulaciones, náuseas', 'Merck'),
 ('FE-00076', 'Prednisona', '5 mg', 'tableta', 'Hormonas', 'Aumento de apetito y peso, insomnio, retención de líquidos', 'Genfar'),
 ('FE-00077', 'Prednisona', '20 mg', 'tableta', 'Hormonas', 'Aumento de apetito y peso, insomnio, retención de líquidos', 'Genfar'),
 ('FE-00078', 'Dexametasona', '0.5 mg', 'tableta', 'Hormonas', 'Aumento de apetito y peso, insomnio, retención de líquidos', 'Genfar'),
 ('FE-00079', 'Dexametasona', '4 mg', 'tableta', 'Hormonas', 'Aumento de apetito y peso, insomnio, retención de líquidos', 'Genfar'),
 ('FE-00080', 'Hidrocortisona', '10 mg', 'tableta', 'Hormonas', 'Aumento de apetito y peso, insomnio, retención de líquidos', 'Pfizer'),
 ('FE-00081', 'Levodopa + carbidopa', '100 mg / 25 mg', 'tableta', 'Neurológicas', 'Náuseas, mareo, movimientos involuntarios', 'MSD'),
 ('FE-00082', 'Levodopa + carbidopa', '250 mg / 25 mg', 'tableta', 'Neurológicas', 'Náuseas, mareo, movimientos involuntarios', 'MSD'),
 ('FE-00083', 'Pramipexol', '0.25 mg', 'tableta', 'Neurológicas', 'Somnolencia, náuseas, mareo', 'Boehringer Ingelheim'),
 ('FE-00084', 'Pramipexol', '1 mg', 'tableta', 'Neurológicas', 'Somnolencia, náuseas, mareo', 'Boehringer Ingelheim'),
 ('FE-00085', 'Biperideno', '2 mg', 'tableta', 'Neurológicas', 'Boca seca, visión borrosa, estreñimiento', 'Abbott'),
 ('FE-00086', 'Donepezilo', '5 mg', 'tableta', 'Neurológicas', 'Náuseas, diarrea, insomnio', 'Eisai'),
 ('FE-00087', 'Donepezilo', '10 mg', 'tableta', 'Neurológicas', 'Náuseas, diarrea, insomnio', 'Eisai'),
 ('FE-00088', 'Memantina', '10 mg', 'tableta', 'Neurológicas', 'Mareo, dolor de cabeza, estreñimiento', 'Lundbeck'),
 ('FE-00089', 'Memantina', '20 mg', 'tableta', 'Neurológicas', 'Mareo, dolor de cabeza, estreñimiento', 'Lundbeck'),
 ('FE-00090', 'Levetiracetam', '500 mg', 'tableta', 'Neurológicas', 'Somnolencia, cansancio, irritabilidad', 'UCB'),
 ('FE-00091', 'Levetiracetam', '1000 mg', 'tableta', 'Neurológicas', 'Somnolencia, cansancio, irritabilidad', 'UCB'),
 ('FE-00092', 'Carbamazepina', '200 mg', 'tableta', 'Neurológicas', 'Mareo, somnolencia, náuseas', 'Novartis'),
 ('FE-00093', 'Carbamazepina', '400 mg', 'tableta', 'Neurológicas', 'Mareo, somnolencia, náuseas', 'Novartis'),
 ('FE-00094', 'Ácido valproico', '250 mg', 'tableta', 'Neurológicas', 'Náuseas, temblor, aumento de peso', 'Sanofi'),
 ('FE-00095', 'Ácido valproico', '500 mg', 'tableta', 'Neurológicas', 'Náuseas, temblor, aumento de peso', 'Sanofi'),
 ('FE-00096', 'Lamotrigina', '25 mg', 'tableta', 'Neurológicas', 'Mareo, dolor de cabeza, erupción en la piel', 'GSK'),
 ('FE-00097', 'Lamotrigina', '100 mg', 'tableta', 'Neurológicas', 'Mareo, dolor de cabeza, erupción en la piel', 'GSK'),
 ('FE-00098', 'Topiramato', '25 mg', 'tableta', 'Neurológicas', 'Hormigueo, somnolencia, pérdida de peso', 'Janssen'),
 ('FE-00099', 'Topiramato', '100 mg', 'tableta', 'Neurológicas', 'Hormigueo, somnolencia, pérdida de peso', 'Janssen'),
 ('FE-00100', 'Sumatriptán', '50 mg', 'tableta', 'Neurológicas', 'Presión en el pecho o cuello, mareo, cansancio', 'GSK'),
 ('FE-00101', 'Sumatriptán', '100 mg', 'tableta', 'Neurológicas', 'Presión en el pecho o cuello, mareo, cansancio', 'GSK'),
 ('FE-00102', 'Fenitoína', '100 mg', 'cápsula', 'Neurológicas', 'Somnolencia, mareo, crecimiento de las encías', 'Pfizer'),
 ('FE-00103', 'Gabapentina', '300 mg', 'cápsula', 'Neurológicas', 'Somnolencia, mareo, hinchazón de piernas', 'Pfizer'),
 ('FE-00104', 'Gabapentina', '400 mg', 'cápsula', 'Neurológicas', 'Somnolencia, mareo, hinchazón de piernas', 'Pfizer'),
 ('FE-00105', 'Pregabalina', '75 mg', 'cápsula', 'Neurológicas', 'Somnolencia, mareo, aumento de peso', 'Pfizer'),
 ('FE-00106', 'Pregabalina', '150 mg', 'cápsula', 'Neurológicas', 'Somnolencia, mareo, aumento de peso', 'Pfizer'),
 ('FE-00107', 'Sertralina', '50 mg', 'tableta', 'Salud mental', 'Náuseas, insomnio, somnolencia', 'Pfizer'),
 ('FE-00108', 'Sertralina', '100 mg', 'tableta', 'Salud mental', 'Náuseas, insomnio, somnolencia', 'Pfizer'),
 ('FE-00109', 'Escitalopram', '10 mg', 'tableta', 'Salud mental', 'Náuseas, insomnio, somnolencia', 'Lundbeck'),
 ('FE-00110', 'Escitalopram', '20 mg', 'tableta', 'Salud mental', 'Náuseas, insomnio, somnolencia', 'Lundbeck'),
 ('FE-00111', 'Amitriptilina', '25 mg', 'tableta', 'Salud mental', 'Boca seca, somnolencia, estreñimiento', 'Genfar'),
 ('FE-00112', 'Clonazepam', '0.5 mg', 'tableta', 'Salud mental', 'Somnolencia, mareo, pérdida de coordinación', 'Roche'),
 ('FE-00113', 'Clonazepam', '2 mg', 'tableta', 'Salud mental', 'Somnolencia, mareo, pérdida de coordinación', 'Roche'),
 ('FE-00114', 'Alprazolam', '0.5 mg', 'tableta', 'Salud mental', 'Somnolencia, mareo, pérdida de coordinación', 'Pfizer'),
 ('FE-00115', 'Alprazolam', '1 mg', 'tableta', 'Salud mental', 'Somnolencia, mareo, pérdida de coordinación', 'Pfizer'),
 ('FE-00116', 'Quetiapina', '25 mg', 'tableta', 'Salud mental', 'Somnolencia, aumento de peso, mareo', 'AstraZeneca'),
 ('FE-00117', 'Quetiapina', '100 mg', 'tableta', 'Salud mental', 'Somnolencia, aumento de peso, mareo', 'AstraZeneca'),
 ('FE-00118', 'Quetiapina', '200 mg', 'tableta', 'Salud mental', 'Somnolencia, aumento de peso, mareo', 'AstraZeneca'),
 ('FE-00119', 'Risperidona', '1 mg', 'tableta', 'Salud mental', 'Somnolencia, aumento de peso, temblor', 'Janssen'),
 ('FE-00120', 'Risperidona', '2 mg', 'tableta', 'Salud mental', 'Somnolencia, aumento de peso, temblor', 'Janssen'),
 ('FE-00121', 'Olanzapina', '5 mg', 'tableta', 'Salud mental', 'Somnolencia, aumento de peso, aumento del apetito', 'Eli Lilly'),
 ('FE-00122', 'Olanzapina', '10 mg', 'tableta', 'Salud mental', 'Somnolencia, aumento de peso, aumento del apetito', 'Eli Lilly'),
 ('FE-00123', 'Haloperidol', '5 mg', 'tableta', 'Salud mental', 'Rigidez muscular, temblor, somnolencia', 'Janssen'),
 ('FE-00124', 'Carbonato de litio', '300 mg', 'tableta', 'Salud mental', 'Sed, temblor, aumento de la orina', 'Genfar'),
 ('FE-00125', 'Fluoxetina', '20 mg', 'cápsula', 'Salud mental', 'Náuseas, insomnio, nerviosismo', 'Eli Lilly'),
 ('FE-00126', 'Salbutamol', '100 mcg/dosis', 'inhalador', 'Respiratorias y alergias', 'Temblor, palpitaciones, dolor de cabeza', 'GSK'),
 ('FE-00127', 'Budesonida + formoterol', '160/4.5 mcg', 'inhalador', 'Respiratorias y alergias', 'Ronquera, hongos en la boca, temblor', 'AstraZeneca'),
 ('FE-00128', 'Budesonida + formoterol', '320/9 mcg', 'inhalador', 'Respiratorias y alergias', 'Ronquera, hongos en la boca, temblor', 'AstraZeneca'),
 ('FE-00129', 'Beclometasona', '250 mcg/dosis', 'inhalador', 'Respiratorias y alergias', 'Ronquera, hongos en la boca, tos', 'Chiesi'),
 ('FE-00130', 'Ipratropio', '20 mcg/dosis', 'inhalador', 'Respiratorias y alergias', 'Boca seca, tos, dolor de cabeza', 'Boehringer Ingelheim'),
 ('FE-00131', 'Tiotropio', '18 mcg', 'cápsula inhalada', 'Respiratorias y alergias', 'Boca seca, tos, estreñimiento', 'Boehringer Ingelheim'),
 ('FE-00132', 'Montelukast', '5 mg', 'tableta', 'Respiratorias y alergias', 'Dolor de cabeza, molestias digestivas, cambios de ánimo', 'MSD'),
 ('FE-00133', 'Montelukast', '10 mg', 'tableta', 'Respiratorias y alergias', 'Dolor de cabeza, molestias digestivas, cambios de ánimo', 'MSD'),
 ('FE-00134', 'Loratadina', '10 mg', 'tableta', 'Respiratorias y alergias', 'Dolor de cabeza, boca seca, cansancio', 'Bayer'),
 ('FE-00135', 'Cetirizina', '10 mg', 'tableta', 'Respiratorias y alergias', 'Somnolencia, boca seca, cansancio', 'UCB'),
 ('FE-00136', 'Omeprazol', '20 mg', 'cápsula', 'Digestivas', 'Dolor de cabeza, diarrea, náuseas', 'AstraZeneca'),
 ('FE-00137', 'Omeprazol', '40 mg', 'cápsula', 'Digestivas', 'Dolor de cabeza, diarrea, náuseas', 'AstraZeneca'),
 ('FE-00138', 'Loperamida', '2 mg', 'cápsula', 'Digestivas', 'Estreñimiento, mareo, náuseas', 'Janssen'),
 ('FE-00139', 'Pantoprazol', '20 mg', 'tableta', 'Digestivas', 'Dolor de cabeza, diarrea, náuseas', 'Takeda'),
 ('FE-00140', 'Pantoprazol', '40 mg', 'tableta', 'Digestivas', 'Dolor de cabeza, diarrea, náuseas', 'Takeda'),
 ('FE-00141', 'Metoclopramida', '10 mg', 'tableta', 'Digestivas', 'Somnolencia, inquietud, diarrea', 'Sanofi'),
 ('FE-00142', 'Lactulosa', '3.35 g/5 ml', 'frasco', 'Digestivas', 'Gases, diarrea, hinchazón', 'Abbott'),
 ('FE-00143', 'Sales de rehidratación oral', '27.9 g', 'sobre', 'Digestivas', 'Náuseas o vómito si se toma muy rápido', 'Genfar'),
 ('FE-00144', 'Paracetamol', '500 mg', 'tableta', 'Dolor y fiebre', 'Bien tolerado; daña el hígado si se excede la dosis', 'GSK'),
 ('FE-00145', 'Ibuprofeno', '400 mg', 'tableta', 'Dolor y fiebre', 'Molestias de estómago, náuseas, mareo', 'Pfizer'),
 ('FE-00146', 'Ibuprofeno', '600 mg', 'tableta', 'Dolor y fiebre', 'Molestias de estómago, náuseas, mareo', 'Pfizer'),
 ('FE-00147', 'Diclofenaco', '50 mg', 'tableta', 'Dolor y fiebre', 'Molestias de estómago, náuseas, mareo', 'Novartis'),
 ('FE-00148', 'Naproxeno', '275 mg', 'tableta', 'Dolor y fiebre', 'Molestias de estómago, náuseas, mareo', 'Bayer'),
 ('FE-00149', 'Naproxeno', '550 mg', 'tableta', 'Dolor y fiebre', 'Molestias de estómago, náuseas, mareo', 'Bayer'),
 ('FE-00150', 'Tramadol', '50 mg', 'cápsula', 'Dolor y fiebre', 'Náuseas, mareo, somnolencia, estreñimiento', 'Grünenthal'),
 ('FE-00151', 'Ketorolaco', '30 mg/ml', 'ampolla', 'Dolor y fiebre', 'Molestias de estómago, mareo, sangrado', 'Roche'),
 ('FE-00152', 'Amoxicilina', '500 mg', 'cápsula', 'Antibióticos y antiinfecciosos', 'Diarrea, náuseas, erupción en la piel', 'GSK'),
 ('FE-00153', 'Cefalexina', '500 mg', 'cápsula', 'Antibióticos y antiinfecciosos', 'Diarrea, náuseas, erupción en la piel', 'Genfar'),
 ('FE-00154', 'Doxiciclina', '100 mg', 'cápsula', 'Antibióticos y antiinfecciosos', 'Náuseas, sensibilidad al sol, molestias digestivas', 'Pfizer'),
 ('FE-00155', 'Nitrofurantoína', '100 mg', 'cápsula', 'Antibióticos y antiinfecciosos', 'Náuseas, dolor de cabeza, orina oscura', 'Genfar'),
 ('FE-00156', 'Fluconazol', '150 mg', 'cápsula', 'Antibióticos y antiinfecciosos', 'Náuseas, dolor de cabeza, dolor abdominal', 'Pfizer'),
 ('FE-00157', 'Amoxicilina + ácido clavulánico', '500/125 mg', 'tableta', 'Antibióticos y antiinfecciosos', 'Diarrea, náuseas, erupción en la piel', 'GSK'),
 ('FE-00158', 'Amoxicilina + ácido clavulánico', '875/125 mg', 'tableta', 'Antibióticos y antiinfecciosos', 'Diarrea, náuseas, erupción en la piel', 'GSK'),
 ('FE-00159', 'Azitromicina', '500 mg', 'tableta', 'Antibióticos y antiinfecciosos', 'Diarrea, náuseas, dolor abdominal', 'Pfizer'),
 ('FE-00160', 'Claritromicina', '500 mg', 'tableta', 'Antibióticos y antiinfecciosos', 'Alteración del gusto, náuseas, diarrea', 'Abbott'),
 ('FE-00161', 'Ciprofloxacino', '500 mg', 'tableta', 'Antibióticos y antiinfecciosos', 'Náuseas, diarrea, dolor en los tendones', 'Bayer'),
 ('FE-00162', 'Trimetoprima + sulfametoxazol', '160/800 mg', 'tableta', 'Antibióticos y antiinfecciosos', 'Náuseas, erupción en la piel, sensibilidad al sol', 'Roche'),
 ('FE-00163', 'Metronidazol', '500 mg', 'tableta', 'Antibióticos y antiinfecciosos', 'Sabor metálico, náuseas, orina oscura', 'Sanofi'),
 ('FE-00164', 'Aciclovir', '400 mg', 'tableta', 'Antibióticos y antiinfecciosos', 'Náuseas, dolor de cabeza, mareo', 'GSK'),
 ('FE-00165', 'Aciclovir', '800 mg', 'tableta', 'Antibióticos y antiinfecciosos', 'Náuseas, dolor de cabeza, mareo', 'GSK'),
 ('FE-00166', 'Albendazol', '400 mg', 'tableta', 'Antibióticos y antiinfecciosos', 'Dolor abdominal, náuseas, dolor de cabeza', 'GSK'),
 ('FE-00167', 'Ceftriaxona', '1 g', 'ampolla', 'Antibióticos y antiinfecciosos', 'Dolor en la zona de inyección, diarrea, erupción en la piel', 'Roche'),
 ('FE-00168', 'Metotrexato', '2.5 mg', 'tableta', 'Reumatología y huesos', 'Náuseas, llagas en la boca, cansancio', 'Pfizer'),
 ('FE-00169', 'Hidroxicloroquina', '200 mg', 'tableta', 'Reumatología y huesos', 'Náuseas, dolor abdominal, alteraciones de la visión', 'Sanofi'),
 ('FE-00170', 'Alopurinol', '100 mg', 'tableta', 'Reumatología y huesos', 'Erupción en la piel, náuseas, diarrea', 'Aspen'),
 ('FE-00171', 'Alopurinol', '300 mg', 'tableta', 'Reumatología y huesos', 'Erupción en la piel, náuseas, diarrea', 'Aspen'),
 ('FE-00172', 'Colchicina', '0.5 mg', 'tableta', 'Reumatología y huesos', 'Diarrea, náuseas, dolor abdominal', 'Genfar'),
 ('FE-00173', 'Alendronato', '70 mg', 'tableta', 'Reumatología y huesos', 'Acidez, dolor al tragar, dolor abdominal', 'MSD'),
 ('FE-00174', 'Calcio + vitamina D', '600 mg / 400 UI', 'tableta', 'Reumatología y huesos', 'Estreñimiento, gases, náuseas', 'Pfizer'),
 ('FE-00175', 'Tamsulosina', '0.4 mg', 'cápsula', 'Urología', 'Mareo, presión baja al levantarse, congestión nasal', 'Astellas'),
 ('FE-00176', 'Finasterida', '5 mg', 'tableta', 'Urología', 'Menor deseo sexual, disfunción eréctil, sensibilidad en las mamas', 'MSD'),
 ('FE-00177', 'Oxibutinina', '5 mg', 'tableta', 'Urología', 'Boca seca, estreñimiento, somnolencia', 'Janssen'),
 ('FE-00178', 'Tamoxifeno', '20 mg', 'tableta', 'Oncología', 'Sofocos, náuseas, flujo vaginal', 'AstraZeneca'),
 ('FE-00179', 'Anastrozol', '1 mg', 'tableta', 'Oncología', 'Sofocos, dolor de articulaciones, cansancio', 'AstraZeneca'),
 ('FE-00180', 'Ácido fólico', '1 mg', 'tableta', 'Vitaminas y suplementos', 'Rara vez náuseas o gases', 'Genfar'),
 ('FE-00181', 'Ácido fólico', '5 mg', 'tableta', 'Vitaminas y suplementos', 'Rara vez náuseas o gases', 'Genfar'),
 ('FE-00182', 'Sulfato ferroso', '300 mg', 'tableta', 'Vitaminas y suplementos', 'Estreñimiento, náuseas, heces oscuras', 'Genfar'),
 ('FE-00183', 'Complejo B', 'B1 + B6 + B12', 'tableta', 'Vitaminas y suplementos', 'Orina amarilla intensa, náuseas leves', 'Merck'),
 ('FE-00184', 'Vitamina B12', '1000 mcg', 'ampolla', 'Vitaminas y suplementos', 'Dolor en la zona de inyección, diarrea leve', 'Genfar'),
 ('FE-00185', 'Vitamina D3', '1000 UI', 'cápsula', 'Vitaminas y suplementos', 'Náuseas, estreñimiento, sed', 'Genfar'),
 ('FE-00186', 'Vitamina D3', '2000 UI', 'cápsula', 'Vitaminas y suplementos', 'Náuseas, estreñimiento, sed', 'Genfar'),
 ('FE-00187', 'Levonorgestrel + etinilestradiol', '0.15 mg / 0.03 mg', 'caja', 'Anticonceptivos', 'Náuseas, dolor de cabeza, sensibilidad en las mamas', 'Bayer')
ON CONFLICT (uid) DO UPDATE SET
    nombre = EXCLUDED.nombre, concentracion = EXCLUDED.concentracion, unidad = EXCLUDED.unidad,
    grupo = EXCLUDED.grupo, efectos_secundarios = EXCLUDED.efectos_secundarios, laboratorio = EXCLUDED.laboratorio;
